spring.application.name=pedidos-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos360_db
spring.datasource.username=pedidos360
spring.datasource.password=pedidos360

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URL del microservicio de Inventario. Cuando lo despleguemos en EC2 y pongamos
# el API Gateway en el medio, este valor pasa a ser el único lugar que cambia.
inventario.service.url=http://localhost:8081
